export { default as Dashboard } from "./Dashboard"
export { default as EvaluationDetails } from "./EvaluationDetails"
export { default as Evaluation } from "./Evaluation"
export {default as UserDetails} from "./UserDetails"
export {default as Analyse} from "./Analyse"
